/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/lesson": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.lesson.id"];
          created_at?: parameters["rowFilter.lesson.created_at"];
          title?: parameters["rowFilter.lesson.title"];
          description?: parameters["rowFilter.lesson.description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["lesson"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** lesson */
          lesson?: definitions["lesson"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.lesson.id"];
          created_at?: parameters["rowFilter.lesson.created_at"];
          title?: parameters["rowFilter.lesson.title"];
          description?: parameters["rowFilter.lesson.description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.lesson.id"];
          created_at?: parameters["rowFilter.lesson.created_at"];
          title?: parameters["rowFilter.lesson.title"];
          description?: parameters["rowFilter.lesson.description"];
        };
        body: {
          /** lesson */
          lesson?: definitions["lesson"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          stripe_customer?: parameters["rowFilter.profile.stripe_customer"];
          email?: parameters["rowFilter.profile.email"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          stripe_customer?: parameters["rowFilter.profile.stripe_customer"];
          email?: parameters["rowFilter.profile.email"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          stripe_customer?: parameters["rowFilter.profile.stripe_customer"];
          email?: parameters["rowFilter.profile.email"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  lesson: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    description?: string;
  };
  profile: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: boolean */
    is_subscribed?: boolean;
    /** Format: text */
    interval?: string;
    /** Format: text */
    stripe_customer?: string;
    /** Format: text */
    email?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description lesson */
  "body.lesson": definitions["lesson"];
  /** Format: bigint */
  "rowFilter.lesson.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.lesson.created_at": string;
  /** Format: text */
  "rowFilter.lesson.title": string;
  /** Format: text */
  "rowFilter.lesson.description": string;
  /** @description profile */
  "body.profile": definitions["profile"];
  /** Format: uuid */
  "rowFilter.profile.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.profile.created_at": string;
  /** Format: boolean */
  "rowFilter.profile.is_subscribed": string;
  /** Format: text */
  "rowFilter.profile.interval": string;
  /** Format: text */
  "rowFilter.profile.stripe_customer": string;
  /** Format: text */
  "rowFilter.profile.email": string;
}

export interface operations {}

export interface external {}
